name: Play Guessing Game

on:
  workflow_dispatch:   # Allows manual trigger from GitHub UI
    inputs:
      guess:
        description: "Enter your guess (1-10)"
        required: true
        default: "5"

jobs:
  play-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run the guessing game
        run: python game.py ${{ github.event.inputs.guess }}