name: Run Game

on:
  push:    # Run when code is pushed
    branches:
      - main

jobs:
  play-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run the guessing game
        run: python guessinggame.py